[config]
  concurrencyLimit = 4
  maxSchemes = 1000

[github]
  colors = [
    "https://github.com/ciaranm/inkpot/tree/master/colors",
    "https://github.com/sjl/badwolf/tree/master/colors",
    "https://github.com/vim-scripts/tabula.vim/tree/master/colors",
    "https://github.com/thinkpixellab/flatland/tree/master/Vim/colors",
    "https://github.com/noahfrederick/vim-hemisu/tree/master/colors",
    "https://github.com/Lokaltog/vim-distinguished/tree/develop/colors",
    "https://github.com/daylerees/colour-schemes/tree/master/vim/colors",
    "https://github.com/w0ng/vim-hybrid/tree/master/colors",
    "https://github.com/chriskempson/vim-tomorrow-theme/tree/master/colors",
    "https://github.com/stefounet/vimfiles/tree/master/colors",
    "https://github.com/29decibel/codeschool-vim-theme/tree/master/colors",
    "https://github.com/guns/jellyx.vim/tree/master/colors",
    "https://github.com/nanotech/jellybeans.vim/tree/master/colors",
    "https://github.com/gmarik/ingretu/tree/master/colors",
    "https://github.com/twerth/ir_black/tree/master/colors",
    "https://github.com/halbtuerke/madeofcode.vim/tree/master/colors",
    "https://github.com/vim-scripts/phphaxor/tree/master/colors",
    "https://github.com/hukl/Smyck-Color-Scheme",
    "https://github.com/sergey-vlasov/codeblocks-dark.vim",
    "https://github.com/nice/sweater/colors",
    "https://github.com/freeo/vim-kalisi/tree/master/colors",
    "https://github.com/junegunn/seoul256.vim/tree/master/colors",
    "https://github.com/tomasr/molokai/tree/master/colors",
    "https://github.com/altercation/solarized/blob/master/vim-colors-solarized/colors",
    "https://github.com/jpo/vim-railscasts-theme/tree/master/colors",
    "https://github.com/joshdick/onedark.vim/tree/master/colors",
    "https://github.com/jnurmine/Zenburn/tree/master/colors",
    "https://github.com/hhsnopek/vim-firewatch/tree/master/colors",
    "https://github.com/juanedi/predawn.vim/tree/master/colors",
    "https://github.com/lifepillar/vim-solarized8/tree/master/colors",
    "https://github.com/owickstrom/vim-colors-paramount/tree/master/colors",
    "https://github.com/limadm/vim-blues/tree/master/colors",
    "https://github.com/jacoborus/tender/tree/master/colors",
    "https://github.com/shaond/vim-guru/tree/master/colors",
    "https://github.com/vim345/vim/tree/master/colors",
    "https://github.com/tristanheaven/vim-colorscheme-aquamarine/tree/master/colors",
    "https://github.com/dfrunza/vim/tree/master/colors",
    "https://github.com/RussellBradley/vim-nets-away/tree/master/colors",
    "https://github.com/RussellBradley/vim-spurs-away/tree/master/colors",
    "https://github.com/RussellBradley/vim-warriors-away/tree/master/colors",
    "https://github.com/tstelzer/welpe.vim/tree/master/colors",
    "https://github.com/notpratheek/vim-luna/tree/master/colors",
    "https://github.com/trevorrjohn/vim-obsidian/tree/master/colors",
    "https://github.com/easysid/mod8.vim/tree/master/colors",
    "https://github.com/mhinz/vim-janah/tree/master/colors",
    "https://github.com/mkarmona/materialbox/tree/master/colors",
    "https://github.com/Donearm/Laederon/tree/master/colors",
    "https://github.com/mkarmona/colorsbox/tree/master/colors",
    "https://github.com/kristijanhusak/vim-hybrid-material/tree/master/colors",
    "https://github.com/keith/parsec.vim/tree/master/colors",
    "https://github.com/chriskempson/base16-vim/tree/master/colors",
    "https://github.com/damage220/solas.vim/tree/master/colors",
    "https://github.com/mhartington/oceanic-next/tree/master/colors",
    "https://github.com/tpope/vim-vividchalk/tree/master/colors",
    "https://github.com/0ax1/lxvc/tree/master/colors",
    "https://github.com/ehartc/Spink/tree/master/colors",
    "https://github.com/romainl/Apprentice/tree/master/colors",
    "https://github.com/zeis/vim-kolor/tree/master/colors",
    "https://github.com/NLKNguyen/papercolor-theme/tree/master/colors",
    "https://github.com/KabbAmine/yowish.vim/tree/master/colors",
    "https://github.com/atelierbram/Base2Tone-vim/tree/master/colors",
    "https://github.com/rakr/vim-two-firewatch/tree/master/colors",
    "https://github.com/sonjapeterson/1989.vim/tree/master/colors",
    "https://github.com/gosukiwi/vim-atom-dark/tree/master/colors",
    "https://github.com/bcicen/vim-vice/tree/master/colors",
    "https://github.com/fcpg/vim-fahrenheit/tree/master/colors",
    "https://github.com/AlessandroYorba/Sierra/tree/master/colors",
    "https://github.com/morhetz/gruvbox/tree/master/colors",
    "https://github.com/AlessandroYorba/Alduin/tree/master/colors",
    "https://github.com/roosta/vim-srcery/tree/master/colors",
    "https://github.com/raphamorim/lucario/tree/master/colors",
    "https://github.com/YorickPeterse/happy_hacking.vim/tree/master/colors",
    "https://github.com/muellan/am-colors/tree/master/colors",
    "https://github.com/dracula/vim/tree/master/colors",
    "https://github.com/gummesson/stereokai.vim/tree/master/colors",
    "https://github.com/wellsjo/wellsokai.vim/tree/master/colors",
    "https://github.com/jonathanfilip/vim-lucius/tree/master/colors",
    "https://github.com/robertmeta/nofrils/tree/master/colors",
    "https://github.com/zefei/cake16/tree/master/colors",
    "https://github.com/reedes/vim-colors-pencil",
    "https://github.com/anhari/octocat.vim/tree/master/colors",
    "https://github.com/mhallendal/spacedust-theme/tree/master/Vim/colors"
  ]
