[config]
  concurrencyLimit = 4
  maxSchemes = 1000
  
[github]
  colors = [
    "https://github.com/ciaranm/inkpot/tree/master/colors",
    "https://github.com/sjl/badwolf/tree/master/colors",
    "https://github.com/vim-scripts/tabula.vim/tree/master/colors",
    "https://github.com/thinkpixellab/flatland/tree/master/Vim/colors",
    "https://github.com/noahfrederick/vim-hemisu/tree/master/colors",
    "https://github.com/Lokaltog/vim-distinguished/tree/develop/colors",
    "https://github.com/daylerees/colour-schemes/tree/master/vim/colors",
    "https://github.com/w0ng/vim-hybrid/tree/master/colors",
    "https://github.com/chriskempson/vim-tomorrow-theme/tree/master/colors",
    "https://github.com/stefounet/vimfiles/tree/master/colors",
    "https://github.com/29decibel/codeschool-vim-theme/tree/master/colors",
    "https://github.com/guns/jellyx.vim/tree/master/colors",
    "https://github.com/nanotech/jellybeans.vim/tree/master/colors",
    "https://github.com/gmarik/ingretu/tree/master/colors",
    "https://github.com/twerth/ir_black/tree/master/colors",
    "https://github.com/halbtuerke/madeofcode.vim/tree/master/colors",
    "https://github.com/vim-scripts/phphaxor/tree/master/colors",
    "https://github.com/hukl/Smyck-Color-Scheme",
    "https://github.com/sergey-vlasov/codeblocks-dark.vim",
    "https://github.com/nice/sweater/colors",
    "https://github.com/freeo/vim-kalisi/tree/master/colors",
    "https://github.com/junegunn/seoul256.vim/tree/master/colors",
    "https://github.com/tomasr/molokai/tree/master/colors",
    "https://github.com/altercation/solarized/blob/master/vim-colors-solarized/colors/solarized.vim",
    "https://github.com/jpo/vim-railscasts-theme/tree/master/colors",
    "https://github.com/joshdick/onedark.vim/tree/master/colors",
    "https://github.com/jnurmine/Zenburn/tree/master/colors",
    "https://github.com/hhsnopek/vim-firewatch/tree/master/colors",
    "https://github.com/juanedi/predawn.vim/tree/master/colors",
    "https://github.com/lifepillar/vim-solarized8/tree/master/colors",
    "https://github.com/owickstrom/vim-colors-paramount/tree/master/colors",
    "https://github.com/limadm/vim-blues/tree/master/colors",
    "https://github.com/jacoborus/tender/tree/master/colors",
    "https://github.com/shaond/vim-guru/tree/master/colors"
  ]
